-- ============================================================================
--  G-SERVICES — V10 : Catalogue (Lot 3, paquetage GestServices)
--  CategorieService → Service (arborescent) → Catalogue → Produit → Article
--  + ProprietesArticle / UniteMesure / VarieteArticle (classe d'association)
--  + produit_proprietes_article (association « définit », n-n)
-- ============================================================================

-- ------------------------------------------------------------ categorie_service
CREATE TABLE categorie_service (
    id_categorie_service BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle              VARCHAR(100) NOT NULL,
    description          VARCHAR(255),
    icone               VARCHAR(60),
    ordre_affichage     INTEGER      NOT NULL DEFAULT 0,
    etat                BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX idx_categorie_service_libelle ON categorie_service (libelle);
CREATE INDEX idx_categorie_service_ordre   ON categorie_service (ordre_affichage);

-- --------------------------------------------------------------------- service
CREATE TABLE service (
    id_service           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle              VARCHAR(120) NOT NULL,
    description          VARCHAR(500),
    image                VARCHAR(160),
    prix_indicatif       DOUBLE PRECISION,
    date_creation        TIMESTAMP    NOT NULL DEFAULT now(),
    etat                 BOOLEAN      NOT NULL DEFAULT TRUE,
    id_categorie_service BIGINT       NOT NULL,
    id_service_parent    BIGINT,
    CONSTRAINT fk_service_categorie FOREIGN KEY (id_categorie_service)
        REFERENCES categorie_service (id_categorie_service),
    CONSTRAINT fk_service_parent FOREIGN KEY (id_service_parent)
        REFERENCES service (id_service) ON DELETE SET NULL
);
CREATE INDEX idx_service_categorie ON service (id_categorie_service);
CREATE INDEX idx_service_parent    ON service (id_service_parent);
CREATE INDEX idx_service_libelle   ON service (libelle);

-- ------------------------------------------------------------------- catalogue
CREATE TABLE catalogue (
    id_catalogue    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle         VARCHAR(120) NOT NULL,
    description     VARCHAR(500),
    icone           VARCHAR(60),
    ordre_affichage INTEGER      NOT NULL DEFAULT 0,
    etat            BOOLEAN      NOT NULL DEFAULT TRUE,
    id_service      BIGINT       NOT NULL,
    CONSTRAINT fk_catalogue_service FOREIGN KEY (id_service) REFERENCES service (id_service)
);
CREATE INDEX idx_catalogue_service ON catalogue (id_service);
CREATE INDEX idx_catalogue_libelle ON catalogue (libelle);

-- ---------------------------------------------------------------- unite_mesure
CREATE TABLE unite_mesure (
    id_unite_mesure BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle         VARCHAR(60) NOT NULL,
    symbole         VARCHAR(12),
    etat            BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_unite_mesure_symbole UNIQUE (symbole)
);
CREATE UNIQUE INDEX idx_unite_mesure_symbole ON unite_mesure (symbole);

-- ------------------------------------------------------------ proprietes_article
CREATE TABLE proprietes_article (
    id_proprietes_article BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle               VARCHAR(100) NOT NULL,
    description           VARCHAR(255),
    type_saisie           VARCHAR(20),
    etat                  BOOLEAN      NOT NULL DEFAULT TRUE,
    id_unite_mesure       BIGINT,
    CONSTRAINT fk_proprietes_article_unite FOREIGN KEY (id_unite_mesure)
        REFERENCES unite_mesure (id_unite_mesure) ON DELETE SET NULL
);
CREATE INDEX idx_proprietes_article_libelle ON proprietes_article (libelle);
CREATE INDEX idx_proprietes_article_unite   ON proprietes_article (id_unite_mesure);

-- --------------------------------------------------------------------- produit
CREATE TABLE produit (
    id_produit    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle       VARCHAR(150) NOT NULL,
    description   VARCHAR(1000),
    image         VARCHAR(160),
    date_creation TIMESTAMP    NOT NULL DEFAULT now(),
    etat          BOOLEAN      NOT NULL DEFAULT TRUE,
    id_catalogue  BIGINT       NOT NULL,
    CONSTRAINT fk_produit_catalogue FOREIGN KEY (id_catalogue) REFERENCES catalogue (id_catalogue)
);
CREATE INDEX idx_produit_catalogue ON produit (id_catalogue);
CREATE INDEX idx_produit_libelle   ON produit (libelle);

-- -------------------------------------------------- produit_proprietes_article (n-n « définit »)
CREATE TABLE produit_proprietes_article (
    id_produit            BIGINT NOT NULL,
    id_proprietes_article BIGINT NOT NULL,
    PRIMARY KEY (id_produit, id_proprietes_article),
    CONSTRAINT fk_ppa_produit FOREIGN KEY (id_produit)
        REFERENCES produit (id_produit) ON DELETE CASCADE,
    CONSTRAINT fk_ppa_proprietes FOREIGN KEY (id_proprietes_article)
        REFERENCES proprietes_article (id_proprietes_article) ON DELETE CASCADE
);
CREATE INDEX idx_ppa_proprietes ON produit_proprietes_article (id_proprietes_article);

-- --------------------------------------------------------------------- article
CREATE TABLE article (
    id_article              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference               VARCHAR(60)   NOT NULL,
    description             VARCHAR(1000),
    prix                    NUMERIC(12,2) NOT NULL DEFAULT 0,
    devise                  VARCHAR(10)   DEFAULT 'XOF',
    mode_vente              VARCHAR(20),
    image                   VARCHAR(160),
    disponibilite           BOOLEAN       NOT NULL DEFAULT TRUE,
    promotion               BOOLEAN       NOT NULL DEFAULT FALSE,
    taux_remise_pourcentage NUMERIC(5,2)  DEFAULT 0,
    date                    TIMESTAMP     NOT NULL DEFAULT now(),
    etat                    BOOLEAN       NOT NULL DEFAULT TRUE,
    id_produit              BIGINT        NOT NULL,
    CONSTRAINT uk_article_reference UNIQUE (reference),
    CONSTRAINT ck_article_remise CHECK (taux_remise_pourcentage >= 0 AND taux_remise_pourcentage <= 100),
    CONSTRAINT fk_article_produit FOREIGN KEY (id_produit) REFERENCES produit (id_produit)
);
CREATE UNIQUE INDEX idx_article_reference ON article (reference);
CREATE INDEX        idx_article_produit   ON article (id_produit);

-- ------------------------------------------------------------- variete_article (classe d'assoc.)
CREATE TABLE variete_article (
    id_variete_article    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valeur                VARCHAR(255),
    etat                  BOOLEAN      NOT NULL DEFAULT TRUE,
    id_article            BIGINT       NOT NULL,
    id_proprietes_article BIGINT       NOT NULL,
    CONSTRAINT uk_variete_article UNIQUE (id_article, id_proprietes_article),
    CONSTRAINT fk_variete_article_article FOREIGN KEY (id_article)
        REFERENCES article (id_article) ON DELETE CASCADE,
    CONSTRAINT fk_variete_article_propriete FOREIGN KEY (id_proprietes_article)
        REFERENCES proprietes_article (id_proprietes_article)
);
CREATE INDEX idx_variete_article_article   ON variete_article (id_article);
CREATE INDEX idx_variete_article_propriete ON variete_article (id_proprietes_article);
