-- ============================================================================
--  G-SERVICES — V13 : Stock & prestataires (Lot 4, paquetage GestServices)
--  Article ─(1-1)─ Stock ─(1-n, composition)─ Lot ─(n-1)─ Mois
--  Service ─(1-1)─ InformationService ─(0-1)─ Position
--                  InformationService ─(1-n)─ Horaire ─(n-1)─ Jour
-- ============================================================================

-- ---------------------------------------------------------------------- stock
CREATE TABLE stock (
    id_stock        BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite_totale INTEGER   NOT NULL DEFAULT 0,
    seuil_alerte    INTEGER   NOT NULL DEFAULT 0,
    date_creation   TIMESTAMP NOT NULL DEFAULT now(),
    etat            BOOLEAN   NOT NULL DEFAULT TRUE,
    id_article      BIGINT    NOT NULL,
    CONSTRAINT uk_stock_article UNIQUE (id_article),
    CONSTRAINT fk_stock_article FOREIGN KEY (id_article)
        REFERENCES article (id_article) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_stock_article ON stock (id_article);

-- ------------------------------------------------------------------------ lot
CREATE TABLE lot (
    id_lot          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_lot      VARCHAR(60)   NOT NULL,
    quantite        INTEGER       NOT NULL DEFAULT 0,
    prix_achat      NUMERIC(12,2),
    date_entree     DATE,
    date_peremption DATE,
    etat            BOOLEAN       NOT NULL DEFAULT TRUE,
    id_stock        BIGINT        NOT NULL,
    id_mois         BIGINT        NOT NULL,
    CONSTRAINT ck_lot_quantite CHECK (quantite >= 0),
    CONSTRAINT fk_lot_stock FOREIGN KEY (id_stock) REFERENCES stock (id_stock) ON DELETE CASCADE,
    CONSTRAINT fk_lot_mois  FOREIGN KEY (id_mois)  REFERENCES mois (id_mois)
);
CREATE INDEX idx_lot_stock  ON lot (id_stock);
CREATE INDEX idx_lot_mois   ON lot (id_mois);
CREATE INDEX idx_lot_numero ON lot (numero_lot);

-- -------------------------------------------------------- information_service
CREATE TABLE information_service (
    id_information_service BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adresse                VARCHAR(255),
    telephone1             VARCHAR(30),
    telephone2             VARCHAR(30),
    email1                 VARCHAR(120),
    email2                 VARCHAR(120),
    site_web               VARCHAR(160),
    disponibilite          BOOLEAN   NOT NULL DEFAULT TRUE,
    date                   TIMESTAMP NOT NULL DEFAULT now(),
    date_maj               TIMESTAMP,
    etat                   BOOLEAN   NOT NULL DEFAULT TRUE,
    id_service             BIGINT    NOT NULL,
    id_position            BIGINT,
    CONSTRAINT uk_info_service_service UNIQUE (id_service),
    CONSTRAINT fk_info_service_service  FOREIGN KEY (id_service)  REFERENCES service (id_service) ON DELETE CASCADE,
    CONSTRAINT fk_info_service_position FOREIGN KEY (id_position) REFERENCES position (id_position) ON DELETE SET NULL
);
CREATE UNIQUE INDEX idx_info_service_service  ON information_service (id_service);
CREATE INDEX        idx_info_service_position ON information_service (id_position);

-- -------------------------------------------------------------------- horaire
CREATE TABLE horaire (
    id_horaire             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heure_ouverture        VARCHAR(5),
    heure_fermeture        VARCHAR(5),
    pause_dejeuner_debut   VARCHAR(5),
    pause_dejeuner_fin     VARCHAR(5),
    ouvert24h              BOOLEAN     NOT NULL DEFAULT FALSE,
    etat                   BOOLEAN     NOT NULL DEFAULT TRUE,
    id_information_service BIGINT      NOT NULL,
    id_jour                BIGINT      NOT NULL,
    CONSTRAINT uk_horaire_info_jour UNIQUE (id_information_service, id_jour),
    CONSTRAINT fk_horaire_info_service FOREIGN KEY (id_information_service)
        REFERENCES information_service (id_information_service) ON DELETE CASCADE,
    CONSTRAINT fk_horaire_jour FOREIGN KEY (id_jour) REFERENCES jour (id_jour)
);
CREATE INDEX idx_horaire_info ON horaire (id_information_service);
CREATE INDEX idx_horaire_jour ON horaire (id_jour);
