-- ============================================================================
--  G-SERVICES — V16 : Avis (Lot 5, classe d'association Personne × Service/Produit)
--  Publié pour une Annee. Visible publiquement seulement si est_modere ET etat.
-- ============================================================================

CREATE TABLE avis (
    id_avis             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note                INTEGER       NOT NULL,
    commentaire         VARCHAR(2000),
    reponse_prestataire VARCHAR(2000),
    est_modere          BOOLEAN       NOT NULL DEFAULT FALSE,
    date                TIMESTAMP     NOT NULL DEFAULT now(),
    etat                BOOLEAN       NOT NULL DEFAULT TRUE,
    id_personne         BIGINT        NOT NULL,
    id_service          BIGINT,
    id_produit          BIGINT,
    id_annee            BIGINT        NOT NULL,
    CONSTRAINT ck_avis_note   CHECK (note BETWEEN 1 AND 5),
    CONSTRAINT ck_avis_cible  CHECK ( (id_service IS NOT NULL) <> (id_produit IS NOT NULL) ),
    CONSTRAINT fk_avis_personne FOREIGN KEY (id_personne) REFERENCES personne (id_personne) ON DELETE CASCADE,
    CONSTRAINT fk_avis_service  FOREIGN KEY (id_service)  REFERENCES service (id_service)  ON DELETE CASCADE,
    CONSTRAINT fk_avis_produit  FOREIGN KEY (id_produit)  REFERENCES produit (id_produit)  ON DELETE CASCADE,
    CONSTRAINT fk_avis_annee    FOREIGN KEY (id_annee)    REFERENCES annee (id_annee),
    -- un avis par personne et par cible
    CONSTRAINT uk_avis_personne_service UNIQUE (id_personne, id_service),
    CONSTRAINT uk_avis_personne_produit UNIQUE (id_personne, id_produit)
);
CREATE INDEX idx_avis_personne ON avis (id_personne);
CREATE INDEX idx_avis_service  ON avis (id_service);
CREATE INDEX idx_avis_produit  ON avis (id_produit);
CREATE INDEX idx_avis_annee    ON avis (id_annee);
CREATE INDEX idx_avis_modere   ON avis (est_modere);
