-- ============================================================================
--  G-SERVICES — V27 : commandes à distance (hors UML)
--
--  Certains services acceptent la vente en ligne (service.commande_a_distance).
--  Un client connecté passe une Commande (n LigneCommande) sur un tel service ;
--  l'administrateur ou le fournisseur propriétaire la traite (branche 7000).
-- ============================================================================

-- ---------------------------------------------------- drapeau service -------
ALTER TABLE service ADD COLUMN IF NOT EXISTS commande_a_distance BOOLEAN NOT NULL DEFAULT FALSE;

-- ---------------------------------------------------- tables ----------------
CREATE TABLE commande (
    id_commande        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference          VARCHAR(30)   NOT NULL UNIQUE,
    date_commande      TIMESTAMP     NOT NULL DEFAULT now(),
    statut             VARCHAR(20)   NOT NULL DEFAULT 'NOUVELLE',
    montant_total      NUMERIC(12,2) NOT NULL DEFAULT 0,
    commentaire        VARCHAR(1000),
    adresse_livraison  VARCHAR(255),
    telephone_contact  VARCHAR(30),
    etat               BOOLEAN       NOT NULL DEFAULT TRUE,
    id_client          BIGINT        NOT NULL,
    id_service         BIGINT        NOT NULL,
    CONSTRAINT fk_commande_client  FOREIGN KEY (id_client)  REFERENCES personne (id_personne),
    CONSTRAINT fk_commande_service FOREIGN KEY (id_service) REFERENCES service (id_service)
);
CREATE INDEX idx_commande_client  ON commande (id_client);
CREATE INDEX idx_commande_service ON commande (id_service);
CREATE INDEX idx_commande_statut  ON commande (statut);

CREATE TABLE ligne_commande (
    id_ligne_commande  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite           INTEGER       NOT NULL CHECK (quantite > 0),
    prix_unitaire      NUMERIC(12,2) NOT NULL,
    etat               BOOLEAN       NOT NULL DEFAULT TRUE,
    id_commande        BIGINT        NOT NULL,
    id_article         BIGINT        NOT NULL,
    CONSTRAINT fk_ligne_commande_commande FOREIGN KEY (id_commande) REFERENCES commande (id_commande) ON DELETE CASCADE,
    CONSTRAINT fk_ligne_commande_article  FOREIGN KEY (id_article)  REFERENCES article (id_article)
);
CREATE INDEX idx_ligne_commande_commande ON ligne_commande (id_commande);

-- ---------------------------------------------------- branche 7000 ----------
INSERT INTO branche_permission (code, libelle, icone, niveau, etat)
VALUES ('7000', 'Commandes', 'pi pi-shopping-cart', 7, TRUE)
ON CONFLICT (code) DO NOTHING;

INSERT INTO permission (code, libelle, action_autorisee, reference, niveau, id_branche_permission)
SELECT v.code, v.libelle, v.action, '/admin/commandes/commandes.xhtml', v.niveau, b.id_branche_permission
FROM (VALUES
    ('7001', 'Consulter les commandes', 'LIRE',       0),
    ('7002', 'Traiter les commandes',   'MODIFIER',   1),
    ('7003', 'Annuler une commande',    'SUPPRIMER',  2),
    ('7004', 'Exporter les commandes',  'EXPORTER',   3)
) AS v(code, libelle, action, niveau)
JOIN branche_permission b ON b.code = '7000'
ON CONFLICT (code) DO NOTHING;

-- SUPER_ADMIN : tout
INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle = 'SUPER_ADMIN' AND pe.code IN ('7001','7002','7003','7004')
ON CONFLICT (id_profil, id_permission) DO NOTHING;

-- ADMIN / GESTIONNAIRE : consulter, traiter, exporter
INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle IN ('ADMIN','GESTIONNAIRE') AND pe.code IN ('7001','7002','7004')
ON CONFLICT (id_profil, id_permission) DO NOTHING;

-- PRESTATAIRE : consulter et traiter (les siennes, via le périmètre)
INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle = 'PRESTATAIRE' AND pe.code IN ('7001','7002')
ON CONFLICT (id_profil, id_permission) DO NOTHING;

INSERT INTO profil_branche_permission (id_profil, id_branche_permission)
SELECT p.id_profil, b.id_branche_permission
FROM profil p JOIN branche_permission b ON b.code = '7000'
WHERE p.libelle IN ('SUPER_ADMIN','ADMIN','GESTIONNAIRE','PRESTATAIRE')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------- démo ------------------
--  Services « vendables en ligne » : restauration, mode & textile, hôtellerie,
--  artisanat, événementiel (produits livrables / réservables à distance).
UPDATE service SET commande_a_distance = TRUE
WHERE id_categorie_service IN (
    SELECT id_categorie_service FROM categorie_service
    WHERE libelle IN ('Restauration', 'Mode & textile', 'Hôtellerie', 'Artisanat', 'Événementiel')
);

--  Quelques commandes de démonstration (clients cl.* / awa.diop … sur des
--  services commandables), 2 articles chacune, statuts variés.
INSERT INTO commande (reference, statut, montant_total, adresse_livraison, telephone_contact, id_client, id_service)
SELECT 'CMD-TMP' || d.rn,
       (ARRAY['NOUVELLE','CONFIRMEE','EN_PREPARATION','LIVREE','NOUVELLE'])[1 + (d.rn % 5)],
       0,
       d.quartier || ', Dakar',
       '+221 77 ' || lpad((100 + d.rn)::text, 3, '0') || ' 00 00',
       d.id_client, d.id_service
FROM (
    SELECT row_number() OVER () AS rn, cl.id_personne AS id_client, s.id_service,
           (ARRAY['Médina','Plateau','Sacré-Cœur','Almadies','Yoff','Ouakam','Point E','Mermoz'])[1 + (row_number() OVER () % 8)] AS quartier
    FROM (SELECT id_personne FROM personne WHERE login LIKE 'cl.%' OR login IN ('awa.diop','karim.ba','marie.ndiaye')) cl
    CROSS JOIN LATERAL (
        SELECT s2.id_service FROM service s2
        WHERE s2.commande_a_distance AND s2.etat AND s2.id_service_parent IS NULL
          AND EXISTS (
              SELECT 1 FROM article ar
              JOIN produit pr ON pr.id_produit = ar.id_produit
              JOIN catalogue ca ON ca.id_catalogue = pr.id_catalogue
              WHERE ca.id_service = s2.id_service AND ar.etat AND ar.disponibilite)
        ORDER BY (cl.id_personne * 7 + s2.id_service) % 97
        LIMIT 1
    ) s
    LIMIT 12
) d;

INSERT INTO ligne_commande (quantite, prix_unitaire, id_commande, id_article)
SELECT 1 + (c.id_commande % 3),
       a.prix,
       c.id_commande,
       a.id_article
FROM commande c
CROSS JOIN LATERAL (
    SELECT ar.id_article, ar.prix
    FROM article ar
    JOIN produit pr ON pr.id_produit = ar.id_produit
    JOIN catalogue ca ON ca.id_catalogue = pr.id_catalogue
    WHERE ca.id_service = c.id_service AND ar.etat AND ar.disponibilite
    ORDER BY ar.id_article
    LIMIT 2
) a
WHERE c.reference LIKE 'CMD-TMP%';

UPDATE commande c
SET montant_total = COALESCE((
    SELECT sum(l.quantite * l.prix_unitaire) FROM ligne_commande l WHERE l.id_commande = c.id_commande
), 0)
WHERE c.reference LIKE 'CMD-TMP%';

UPDATE commande SET reference = 'CMD-' || lpad(id_commande::text, 6, '0')
WHERE reference LIKE 'CMD-TMP%';
