-- ============================================================================
--  G-SERVICES — V2 : paquetage GestUser (Lot 1)
--  Personne, Sexe(enum->varchar), Profil, Permission, BranchePermission,
--  Role (classe d'assoc. Personne x Profil), RoleProfil (classe d'assoc.
--  Profil x Permission), + table de jonction Profil x BranchePermission.
-- ============================================================================

-- ------------------------------------------------------------------ personne
CREATE TABLE personne (
    id_personne          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom                  VARCHAR(80)  NOT NULL,
    prenom               VARCHAR(80)  NOT NULL,
    sexe                 VARCHAR(10),
    date_naissance       DATE,
    lieu_naissance       VARCHAR(120),
    nationalite          VARCHAR(80),
    adresse              VARCHAR(255),
    code_postal          VARCHAR(20),
    telephone1           VARCHAR(30),
    telephone2           VARCHAR(30),
    telephone3           VARCHAR(30),
    email1               VARCHAR(150),
    email2               VARCHAR(150),
    login                VARCHAR(60)  NOT NULL,
    password             VARCHAR(100) NOT NULL,
    photo_profil         VARCHAR(255),
    date_inscription     TIMESTAMP    NOT NULL DEFAULT now(),
    derniere_connexion   TIMESTAMP,
    tentatives_echouees  INTEGER      NOT NULL DEFAULT 0,
    verrouille_jusqua    TIMESTAMP,
    etat                 BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_personne_login UNIQUE (login),
    CONSTRAINT ck_personne_sexe  CHECK (sexe IS NULL OR sexe IN ('HOMME', 'FEMME'))
);
CREATE UNIQUE INDEX idx_personne_login  ON personne (login);
CREATE INDEX        idx_personne_email1 ON personne (email1);
CREATE INDEX        idx_personne_nom    ON personne (nom);
COMMENT ON COLUMN personne.password IS 'Hash BCrypt';
COMMENT ON COLUMN personne.tentatives_echouees IS 'Hors UML — règle de verrouillage après N échecs';
COMMENT ON COLUMN personne.verrouille_jusqua   IS 'Hors UML — fin de verrouillage du compte';

-- -------------------------------------------------------------------- profil
CREATE TABLE profil (
    id_profil    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle      VARCHAR(80)  NOT NULL,
    description  VARCHAR(255),
    niveau       INTEGER      NOT NULL DEFAULT 100,
    date         TIMESTAMP    NOT NULL DEFAULT now(),
    date_maj     TIMESTAMP,
    etat         BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_profil_libelle UNIQUE (libelle)
);
CREATE UNIQUE INDEX idx_profil_libelle ON profil (libelle);

-- --------------------------------------------------------- branche_permission
CREATE TABLE branche_permission (
    id_branche_permission BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                  VARCHAR(60)  NOT NULL,
    libelle               VARCHAR(100) NOT NULL,
    icone                 VARCHAR(60),
    reference             VARCHAR(150),
    niveau                INTEGER      NOT NULL DEFAULT 0,
    date                  TIMESTAMP    NOT NULL DEFAULT now(),
    date_maj              TIMESTAMP,
    etat                  BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_branche_code UNIQUE (code)
);
CREATE UNIQUE INDEX idx_branche_code ON branche_permission (code);

-- ---------------------------------------------------------------- permission
CREATE TABLE permission (
    id_permission          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   VARCHAR(100) NOT NULL,
    libelle                VARCHAR(120) NOT NULL,
    action_autorisee       VARCHAR(40),
    reference              VARCHAR(150),
    niveau                 INTEGER      NOT NULL DEFAULT 0,
    date                   TIMESTAMP    NOT NULL DEFAULT now(),
    date_maj               TIMESTAMP,
    etat                   BOOLEAN      NOT NULL DEFAULT TRUE,
    id_branche_permission  BIGINT,
    CONSTRAINT uk_permission_code UNIQUE (code),
    CONSTRAINT fk_permission_branche FOREIGN KEY (id_branche_permission)
        REFERENCES branche_permission (id_branche_permission)
);
CREATE UNIQUE INDEX idx_permission_code    ON permission (code);
CREATE INDEX        idx_permission_branche ON permission (id_branche_permission);

-- ---------------------------------------------------------------------- role
--  Classe d'association datée : Personne x Profil
CREATE TABLE role (
    id_role          BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_personne      BIGINT    NOT NULL,
    id_profil        BIGINT    NOT NULL,
    date_attribution TIMESTAMP NOT NULL DEFAULT now(),
    date_maj         TIMESTAMP,
    etat             BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_role_personne_profil UNIQUE (id_personne, id_profil),
    CONSTRAINT fk_role_personne FOREIGN KEY (id_personne) REFERENCES personne (id_personne),
    CONSTRAINT fk_role_profil   FOREIGN KEY (id_profil)   REFERENCES profil (id_profil)
);
CREATE INDEX idx_role_personne ON role (id_personne);
CREATE INDEX idx_role_profil   ON role (id_profil);

-- --------------------------------------------------------------- role_profil
--  Classe d'association datée : Profil x Permission
CREATE TABLE role_profil (
    id_role_profil    BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_profil         BIGINT    NOT NULL,
    id_permission     BIGINT    NOT NULL,
    date_affectation  TIMESTAMP NOT NULL DEFAULT now(),
    date_maj          TIMESTAMP,
    etat              BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_role_profil_profil_permission UNIQUE (id_profil, id_permission),
    CONSTRAINT fk_role_profil_profil     FOREIGN KEY (id_profil)     REFERENCES profil (id_profil),
    CONSTRAINT fk_role_profil_permission FOREIGN KEY (id_permission) REFERENCES permission (id_permission)
);
CREATE INDEX idx_role_profil_profil     ON role_profil (id_profil);
CREATE INDEX idx_role_profil_permission ON role_profil (id_permission);

-- ------------------------------------------------- profil_branche_permission
--  Jonction n-n : Profil <-> BranchePermission (sections de menu autorisées)
CREATE TABLE profil_branche_permission (
    id_profil             BIGINT NOT NULL,
    id_branche_permission BIGINT NOT NULL,
    PRIMARY KEY (id_profil, id_branche_permission),
    CONSTRAINT fk_pbp_profil FOREIGN KEY (id_profil)
        REFERENCES profil (id_profil) ON DELETE CASCADE,
    CONSTRAINT fk_pbp_branche FOREIGN KEY (id_branche_permission)
        REFERENCES branche_permission (id_branche_permission) ON DELETE CASCADE
);
CREATE INDEX idx_pbp_branche ON profil_branche_permission (id_branche_permission);
