-- ============================================================================
--  G-SERVICES — V30 : espaces favoris (classe d'association Personne × Service)
--
--  Nouveau cahier « Application Web/Mobile de Localisation Temps Réel de
--  Ressources et Services » — §3 Administration : « Gestion des espaces
--  favoris ». Un client marque un service en favori (auto-service, comme les
--  avis) ; consultable dans « Mes favoris » (web + mobile).
-- ============================================================================

CREATE TABLE favori (
    id_favori   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_ajout  TIMESTAMP   NOT NULL DEFAULT now(),
    etat        BOOLEAN     NOT NULL DEFAULT TRUE,
    id_personne BIGINT      NOT NULL,
    id_service  BIGINT      NOT NULL,
    CONSTRAINT fk_favori_personne FOREIGN KEY (id_personne) REFERENCES personne (id_personne) ON DELETE CASCADE,
    CONSTRAINT fk_favori_service  FOREIGN KEY (id_service)  REFERENCES service (id_service)  ON DELETE CASCADE,
    CONSTRAINT uk_favori_personne_service UNIQUE (id_personne, id_service)
);
CREATE INDEX idx_favori_personne ON favori (id_personne);
CREATE INDEX idx_favori_service  ON favori (id_service);

-- ---------------------------------------------------- démo : quelques favoris
INSERT INTO favori (id_personne, id_service, date_ajout, etat)
SELECT p.id_personne, s.id_service, now() - (random() * interval '20 days'), TRUE
FROM personne p
JOIN LATERAL (
    SELECT id_service FROM service
    WHERE etat AND valide
    ORDER BY random() LIMIT 3
) s ON TRUE
WHERE p.login IN ('awa.diop', 'karim.ba', 'marie.ndiaye', 'cl.sarr', 'cl.toure', 'cl.wade', 'cl.gomis')
ON CONFLICT (id_personne, id_service) DO NOTHING;
