-- ============================================================================
--  G-SERVICES — V31 : système de sanction / surveillance de la plateforme
--
--  Nouveau cahier §3 Administration : « Système de sanction (surveillance de la
--  plateforme) », « Gérer les interdictions et blocages de services signalés ».
--   - un client signale un service (Signalement, classe d'association hors UML
--     Personne × Service) ;
--   - un administrateur l'examine : rejette, ou sanctionne (Sanction = journal
--     d'audit du blocage, hors UML) ;
--   - `service.bloque = true` tant que la sanction est active -> masqué du front
--     public (comme `valide = false`), sans suppression physique.
-- ============================================================================

ALTER TABLE service ADD COLUMN IF NOT EXISTS bloque BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE signalement (
    id_signalement BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motif          VARCHAR(40) NOT NULL,
    description    VARCHAR(1000),
    date           TIMESTAMP   NOT NULL DEFAULT now(),
    statut         VARCHAR(20) NOT NULL DEFAULT 'NOUVEAU',
    etat           BOOLEAN     NOT NULL DEFAULT TRUE,
    id_personne    BIGINT      NOT NULL,
    id_service     BIGINT      NOT NULL,
    CONSTRAINT fk_signalement_personne FOREIGN KEY (id_personne) REFERENCES personne (id_personne) ON DELETE CASCADE,
    CONSTRAINT fk_signalement_service  FOREIGN KEY (id_service)  REFERENCES service (id_service)  ON DELETE CASCADE
);
CREATE INDEX idx_signalement_service ON signalement (id_service);
CREATE INDEX idx_signalement_statut  ON signalement (statut);

CREATE TABLE sanction (
    id_sanction   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motif         VARCHAR(500) NOT NULL,
    date_sanction TIMESTAMP    NOT NULL DEFAULT now(),
    date_levee    TIMESTAMP,
    etat          BOOLEAN      NOT NULL DEFAULT TRUE,
    id_service    BIGINT       NOT NULL,
    id_admin      BIGINT,
    CONSTRAINT fk_sanction_service FOREIGN KEY (id_service) REFERENCES service (id_service) ON DELETE CASCADE,
    CONSTRAINT fk_sanction_admin   FOREIGN KEY (id_admin)   REFERENCES personne (id_personne) ON DELETE SET NULL
);
CREATE INDEX idx_sanction_service ON sanction (id_service);

-- ---------------------------------------------------- permissions (branche 6000)
INSERT INTO permission (code, libelle, action_autorisee, reference, niveau, id_branche_permission)
SELECT v.code, v.libelle, v.action, '/admin/avis/moderation.xhtml', v.niveau, b.id_branche_permission
FROM (VALUES
    ('6007', 'Consulter les signalements',          'LIRE',        6),
    ('6008', 'Sanctionner / bloquer un service',    'ADMINISTRER', 7)
) AS v(code, libelle, action, niveau)
JOIN branche_permission b ON b.code = '6000'
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle = 'SUPER_ADMIN' AND pe.code IN ('6007', '6008')
ON CONFLICT (id_profil, id_permission) DO NOTHING;

INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle = 'ADMIN' AND pe.code IN ('6007', '6008')
ON CONFLICT (id_profil, id_permission) DO NOTHING;

-- GESTIONNAIRE : consultation seule (bloquer un service reste réservé à ADMIN+)
INSERT INTO role_profil (id_profil, id_permission)
SELECT p.id_profil, pe.id_permission
FROM profil p CROSS JOIN permission pe
WHERE p.libelle = 'GESTIONNAIRE' AND pe.code = '6007'
ON CONFLICT (id_profil, id_permission) DO NOTHING;

-- ---------------------------------------------------- démo : quelques signalements
INSERT INTO signalement (motif, description, date, statut, id_personne, id_service)
SELECT v.motif, v.descr, now() - (v.jours || ' days')::interval, 'NOUVEAU',
       (SELECT id_personne FROM personne WHERE login = v.rapporteur),
       (SELECT id_service FROM service WHERE libelle = v.service_libelle)
FROM (VALUES
    ('INFORMATIONS_ERRONEES', 'L''adresse indiquée ne correspond plus au local du prestataire.', 3, 'cl.sarr', 'Garage Auto Sy'),
    ('SERVICE_INDISPONIBLE',  'Prestataire injoignable depuis plusieurs jours, aucune réponse.', 1, 'cl.toure', 'Coursiers Express'),
    ('CONTENU_INAPPROPRIE',   'Photos de profil sans rapport avec le service proposé.', 5, 'awa.diop', 'Studio Photo Camara')
) AS v(motif, descr, jours, rapporteur, service_libelle)
WHERE EXISTS (SELECT 1 FROM personne WHERE login = v.rapporteur)
  AND EXISTS (SELECT 1 FROM service WHERE libelle = v.service_libelle);
