-- ============================================================================
--  G-SERVICES — V6 : surcharges de permissions par utilisateur (hors UML)
--  Permet de cocher/décocher, pour UNE personne, une permission par-dessus
--  celles héritées de ses profils (accordee=true : ajoutée ; false : retirée).
-- ============================================================================

CREATE TABLE personne_permission (
    id_personne_permission BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_personne             BIGINT    NOT NULL,
    id_permission           BIGINT    NOT NULL,
    accordee                BOOLEAN   NOT NULL DEFAULT TRUE,
    date_creation           TIMESTAMP NOT NULL DEFAULT now(),
    date_maj                TIMESTAMP,
    etat                    BOOLEAN   NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_personne_permission UNIQUE (id_personne, id_permission),
    CONSTRAINT fk_pp_personne   FOREIGN KEY (id_personne)   REFERENCES personne (id_personne)     ON DELETE CASCADE,
    CONSTRAINT fk_pp_permission FOREIGN KEY (id_permission) REFERENCES permission (id_permission)  ON DELETE CASCADE
);
CREATE INDEX idx_pp_personne   ON personne_permission (id_personne);
CREATE INDEX idx_pp_permission ON personne_permission (id_permission);

COMMENT ON TABLE personne_permission IS
    'Hors UML — surcharge de permission par utilisateur (grant/deny au-dessus des profils).';
