-- ============================================================================
--  G-SERVICES — V7 : Géographie & temps (Lot 2, paquetage GestServices)
--  Continent → ZoneGeographique → Pays → Region → Ville → Position
--  + Jour (référentiel), Annee, Mois.
-- ============================================================================

-- ------------------------------------------------------------------ continent
CREATE TABLE continent (
    id_continent    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle         VARCHAR(80)  NOT NULL,
    code            VARCHAR(10),
    superficie_km2  DOUBLE PRECISION,
    population      BIGINT,
    date_creation   TIMESTAMP    NOT NULL DEFAULT now(),
    etat            BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_continent_code UNIQUE (code)
);
CREATE UNIQUE INDEX idx_continent_code    ON continent (code);
CREATE INDEX        idx_continent_libelle ON continent (libelle);

-- ----------------------------------------------------------- zone_geographique
CREATE TABLE zone_geographique (
    id_zone_geographique BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle              VARCHAR(80)  NOT NULL,
    code                 VARCHAR(10),
    description          VARCHAR(255),
    date_creation        TIMESTAMP    NOT NULL DEFAULT now(),
    etat                 BOOLEAN      NOT NULL DEFAULT TRUE,
    id_continent         BIGINT       NOT NULL,
    CONSTRAINT uk_zone_code    UNIQUE (code),
    CONSTRAINT fk_zone_continent FOREIGN KEY (id_continent) REFERENCES continent (id_continent)
);
CREATE UNIQUE INDEX idx_zone_code      ON zone_geographique (code);
CREATE INDEX        idx_zone_continent ON zone_geographique (id_continent);

-- ---------------------------------------------------------------------- pays
CREATE TABLE pays (
    id_pays                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle                VARCHAR(100) NOT NULL,
    code_iso2              VARCHAR(2),
    code_iso3              VARCHAR(3),
    indicatif_telephonique VARCHAR(10),
    devise                 VARCHAR(10),
    capitale               VARCHAR(100),
    langue_officielle      VARCHAR(80),
    superficie_km2         DOUBLE PRECISION,
    population             BIGINT,
    drapeau                VARCHAR(120),
    date_creation          TIMESTAMP    NOT NULL DEFAULT now(),
    etat                   BOOLEAN      NOT NULL DEFAULT TRUE,
    id_zone_geographique   BIGINT       NOT NULL,
    CONSTRAINT uk_pays_iso2 UNIQUE (code_iso2),
    CONSTRAINT uk_pays_iso3 UNIQUE (code_iso3),
    CONSTRAINT fk_pays_zone FOREIGN KEY (id_zone_geographique)
        REFERENCES zone_geographique (id_zone_geographique)
);
CREATE UNIQUE INDEX idx_pays_iso2    ON pays (code_iso2);
CREATE UNIQUE INDEX idx_pays_iso3    ON pays (code_iso3);
CREATE INDEX        idx_pays_zone    ON pays (id_zone_geographique);
CREATE INDEX        idx_pays_libelle ON pays (libelle);

-- -------------------------------------------------------------------- region
CREATE TABLE region (
    id_region       BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle         VARCHAR(100) NOT NULL,
    code_region     VARCHAR(20),
    chef_lieu       VARCHAR(100),
    superficie_km2  DOUBLE PRECISION,
    population      BIGINT,
    date_creation   TIMESTAMP    NOT NULL DEFAULT now(),
    etat            BOOLEAN      NOT NULL DEFAULT TRUE,
    id_pays         BIGINT       NOT NULL,
    CONSTRAINT fk_region_pays FOREIGN KEY (id_pays) REFERENCES pays (id_pays)
);
CREATE INDEX idx_region_code    ON region (code_region);
CREATE INDEX idx_region_pays    ON region (id_pays);
CREATE INDEX idx_region_libelle ON region (libelle);

-- --------------------------------------------------------------------- ville
CREATE TABLE ville (
    id_ville        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle         VARCHAR(100) NOT NULL,
    code_postal     VARCHAR(20),
    indicatif_zone  VARCHAR(20),
    population      BIGINT,
    superficie_km2  DOUBLE PRECISION,
    est_capitale    BOOLEAN      NOT NULL DEFAULT FALSE,
    date_creation   TIMESTAMP    NOT NULL DEFAULT now(),
    etat            BOOLEAN      NOT NULL DEFAULT TRUE,
    id_region       BIGINT       NOT NULL,
    CONSTRAINT fk_ville_region FOREIGN KEY (id_region) REFERENCES region (id_region)
);
CREATE INDEX idx_ville_region  ON ville (id_region);
CREATE INDEX idx_ville_libelle ON ville (libelle);
CREATE INDEX idx_ville_cp      ON ville (code_postal);

-- ------------------------------------------------------------------ position
CREATE TABLE position (
    id_position      BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude         DOUBLE PRECISION NOT NULL,
    longitude        DOUBLE PRECISION NOT NULL,
    altitude         DOUBLE PRECISION,
    precision_metres DOUBLE PRECISION,
    date_releve      DATE,
    etat             BOOLEAN          NOT NULL DEFAULT TRUE,
    id_ville         BIGINT           NOT NULL,
    CONSTRAINT fk_position_ville FOREIGN KEY (id_ville) REFERENCES ville (id_ville) ON DELETE CASCADE
);
CREATE INDEX idx_position_ville ON position (id_ville);

-- ---------------------------------------------------------------------- jour
CREATE TABLE jour (
    id_jour             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle             VARCHAR(20) NOT NULL,
    abreviation         VARCHAR(5),
    numero_jour_semaine INTEGER     NOT NULL,
    est_weekend         BOOLEAN     NOT NULL DEFAULT FALSE,
    est_ferie           BOOLEAN     NOT NULL DEFAULT FALSE,
    etat                BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_jour_numero UNIQUE (numero_jour_semaine)
);
CREATE UNIQUE INDEX idx_jour_numero ON jour (numero_jour_semaine);

-- --------------------------------------------------------------------- annee
CREATE TABLE annee (
    id_annee       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle        VARCHAR(20) NOT NULL,
    valeur_annee   INTEGER     NOT NULL,
    est_bissextile BOOLEAN     NOT NULL DEFAULT FALSE,
    date_debut     DATE,
    date_fin       DATE,
    etat           BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_annee_valeur UNIQUE (valeur_annee)
);
CREATE UNIQUE INDEX idx_annee_valeur ON annee (valeur_annee);

-- ---------------------------------------------------------------------- mois
CREATE TABLE mois (
    id_mois      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle      VARCHAR(20) NOT NULL,
    abreviation  VARCHAR(5),
    numero_mois  INTEGER     NOT NULL,
    nombre_jours INTEGER     NOT NULL,
    etat         BOOLEAN     NOT NULL DEFAULT TRUE,
    id_annee     BIGINT      NOT NULL,
    CONSTRAINT uk_mois_annee_numero UNIQUE (id_annee, numero_mois),
    CONSTRAINT fk_mois_annee FOREIGN KEY (id_annee) REFERENCES annee (id_annee) ON DELETE CASCADE
);
CREATE INDEX idx_mois_annee ON mois (id_annee);
